cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'zsh'
brew 'coreutils'
brew 'grc'
brew 'libgit2'
brew 'openssl'
brew 'ncdu'
brew 'deno'
brew 'nvm'
brew 'pnpm'
brew 'readline'
brew 'postgresql'
brew 'spaceman-diff'
brew 'wget'
brew 'youtube-dl'
brew 'elixir'
brew 'rustup'
# brew 'mas'
brew 'watchman'

cask 'obsidian'
cask 'linearmouse'
cask 'rectangle'
cask '1password'
cask 'visual-studio-code'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'vlc'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'istat-menus'
cask 'backblaze'
cask 'little-snitch'
cask 'iterm2'
cask 'docker'
cask 'the-unarchiver'
cask 'flux'
cask 'spotify'
cask 'launchrocket'
cask 'figma'
cask 'discord'
cask 'android-studio'
cask 'ukelele'
cask 'cursor'