cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'ack'
brew 'zsh'
brew 'coreutils'
brew 'grc'
brew 'libgit2'
brew 'openssl'
brew 'ncdu'
# brew 'nvm' installed through lukechilds/zsh-nvm through antigen
brew 'readline'
brew 'postgresql'
brew 'spaceman-diff'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'
brew 'elixir'
brew 'git-flow'
# brew 'mas'
brew 'watchman'

cask '1password'
cask 'visual-studio-code'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'hazel3'
cask 'vlc'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'bettertouchtool'
cask 'keyboardcleantool'
cask 'istat-menus'
cask 'backblaze'
cask 'little-snitch'
cask 'iterm2'
cask 'airflow'
cask 'dash'
cask 'docker'
cask 'the-unarchiver'
cask 'flux'
cask 'spotify'
cask 'launchrocket'
cask 'figma'